### ISSUE TITLE
keeps crashing and i'm unsure why

### ISSUE THREAD

**Issue by oshinowo-stephen** [ryansheehan/terraria#114]
So... i'm over here trying to run this server on a simple raspPi and i kept running into this error and i'm unsure if i'm supposed to contact you or https://github.com/Pryaxis/TShock but i'm just here for now:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
terraria_1  |   at Terraria.Main.startDedInputCallBack () [0x00017] in <0fcd5f39a6264235b839ac215b842ba8>:0
terraria_1  |   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <533173d24dae460899d2b10975534bb0>:0
terraria_1  |   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <533173d24dae460899d2b10975534bb0>:0
terraria_1  |   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <533173d24dae460899d2b10975534bb0>:0
terraria_1  |   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <533173d24dae460899d2b10975534bb0>:0
terraria_1  |   at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <533173d24dae460899d2b10975534bb0>:0
```

if you're also unsure I can try to run over to tshock and see if i can figure out something over there

**Comment by hakusaro** [comment]
Cross-posting here: this is caused by the server command thread running probably: https://github.com/Pryaxis/TShock/discussions/2524#discussioncomment-1726321

**Comment by oshinowo-stephen** [comment]
thank you for your service! the final config looks something like this:
```yml
terraria:
    image: ryshe/terraria
    ports:
      - "7777:7777"
    environment:
      WORLD_FILENAME: FrenchFries.wld
    volumes:
      - /home/satori/world-mania/terraria:/root/.local/share/Terraria/Worlds
    command:
      - -disable-commands
 ```
