### ISSUE TITLE
Swarm - bypass options

### ISSUE THREAD

**Issue by Felipenho** [ryansheehan/terraria#31]
Hello Ryan,

Do you possibly have any workarounds to work with docker swarm?

The default options as create a new world, choosing the size and etc.?

I was building the image to the latest TShock 4.4.0 

I Expect some errors to appear, as they didn't really support 1.4.0.2 at the moment, but... maybe this should work ? xD

```YAML
services:
  terraria:
    image: terraria-server:1.4.02
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4096M
      mode: global
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    environment:
    - "-world /world/Taverna.wld"
    networks:
    - terraria
    volumes:
    - /home/ubuntu/terraria/world:/world
    ports:
    - "7777:7777"

networks:
  terraria:
    external: true

```
